// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PulseCheck.Infrastructure.Persistence;

#nullable disable

namespace PulseCheck.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulseCheckDbContext))]
    [Migration("20260625165628_AddEmployeeIdentityFields")]
    partial class AddEmployeeIdentityFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PulseCheck.Domain.Entities.AdminSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AdminSessions", (string)null);
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthenticationMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.AgentActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("IdleSecondsAtLock")
                        .HasColumnType("int");

                    b.Property<string>("LockReason")
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("AgentActivityEvents", (string)null);
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<TimeOnly>("DeliveryWindowEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("DeliveryWindowStart")
                        .HasColumnType("time");

                    b.Property<int>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int>("MinValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuestionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleRule")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f0f8595-44ae-4f1e-ae98-a098ac2bd601"),
                            Audience = "Operaciones y soporte",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 18, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "HR Team",
                            DeliveryWindowEnd = new TimeOnly(11, 30, 0),
                            DeliveryWindowStart = new TimeOnly(9, 0, 0),
                            MaxValue = 5,
                            MinValue = 1,
                            Name = "Pulso diario de bienestar",
                            QuestionText = "De 1 a 5, como te sientes hoy?",
                            QuestionsJson = "[{\"id\":\"ca1508ea-1827-4f34-a846-f2f78da30603\",\"text\":\"De 1 a 5, como te sientes hoy?\",\"type\":\"Scale\",\"minValue\":1,\"maxValue\":5,\"placeholder\":null}]",
                            ScheduleRule = "0 0 10 ? * MON-FRI",
                            Status = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 23, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5cd9666b-b621-46d9-a2b7-2ae8db4decc8"),
                            Audience = "Team leads",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 13, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "People Ops",
                            DeliveryWindowEnd = new TimeOnly(16, 0, 0),
                            DeliveryWindowStart = new TimeOnly(14, 0, 0),
                            MaxValue = 5,
                            MinValue = 1,
                            Name = "Chequeo semanal de carga",
                            QuestionText = "Como percibes tu carga de trabajo esta semana?",
                            QuestionsJson = "[{\"id\":\"7470b44d-cf1e-4964-9f7e-4476655f2723\",\"text\":\"Como percibes tu carga de trabajo esta semana?\",\"type\":\"Scale\",\"minValue\":1,\"maxValue\":5,\"placeholder\":null}]",
                            ScheduleRule = "0 30 15 ? * FRI",
                            Status = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 20, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("4ec08ed3-257a-40bf-ac31-78cab5bd4fa4"),
                            Audience = "Leadership Medellin",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 24, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "PMO",
                            DeliveryWindowEnd = new TimeOnly(12, 0, 0),
                            DeliveryWindowStart = new TimeOnly(10, 0, 0),
                            MaxValue = 5,
                            MinValue = 1,
                            Name = "Piloto liderazgo Medellin",
                            QuestionText = "Que tan clara fue la comunicacion de esta semana?",
                            QuestionsJson = "[{\"id\":\"dcd5e7df-1ea6-4fc7-b4ad-f983013f4de7\",\"text\":\"Que tan clara fue la comunicacion de esta semana?\",\"type\":\"Scale\",\"minValue\":1,\"maxValue\":5,\"placeholder\":null}]",
                            ScheduleRule = "0 0 11 ? * TUE",
                            Status = 0,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 25, 8, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.DeliveryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("PromptedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("nvarchar(48)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("DeliveryLogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("441f71d5-2689-4387-bd91-177344670e1c"),
                            CampaignId = new Guid("7f0f8595-44ae-4f1e-ae98-a098ac2bd601"),
                            DeviceId = "pc-bog-001",
                            Email = "ana.torres@company.com",
                            Hostname = "PC-BOG-001",
                            PromptedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 25, 14, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            RetryCount = 0,
                            Status = "Answered",
                            UserId = "u-001",
                            UserName = "Ana Torres"
                        },
                        new
                        {
                            Id = new Guid("f4ddd0f9-48b2-4304-8f9f-3eae66b25456"),
                            CampaignId = new Guid("5cd9666b-b621-46d9-a2b7-2ae8db4decc8"),
                            DeviceId = "pc-med-021",
                            Email = "luis.perez@company.com",
                            Hostname = "PC-MED-021",
                            PromptedAtUtc = new DateTimeOffset(new DateTime(2026, 6, 25, 16, 21, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            RetryCount = 0,
                            Status = "Prompted",
                            UserId = "u-002",
                            UserName = "Luis Perez"
                        });
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EntraObjectId");

                    b.ToTable("Devices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4da0bf8-aea6-4514-8c12-5183877d7820"),
                            AgentVersion = "0.1.0",
                            Department = "Operaciones",
                            DeviceId = "pc-bog-001",
                            Email = "ana.torres@company.com",
                            EmployeeId = "",
                            EntraObjectId = "",
                            FirstSeenAtUtc = new DateTimeOffset(new DateTime(2026, 6, 18, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            Hostname = "PC-BOG-001",
                            LastSeenAtUtc = new DateTimeOffset(new DateTime(2026, 6, 25, 16, 36, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            OperatingSystem = "Windows 11",
                            UserId = "u-001",
                            UserName = "Ana Torres",
                            UserPrincipalName = ""
                        },
                        new
                        {
                            Id = new Guid("9eb2924d-c67d-4b4c-8482-b4d2ed6ca1de"),
                            AgentVersion = "0.1.0",
                            Department = "Soporte",
                            DeviceId = "pc-med-021",
                            Email = "luis.perez@company.com",
                            EmployeeId = "",
                            EntraObjectId = "",
                            FirstSeenAtUtc = new DateTimeOffset(new DateTime(2026, 6, 21, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            Hostname = "PC-MED-021",
                            LastSeenAtUtc = new DateTimeOffset(new DateTime(2026, 6, 25, 16, 44, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            OperatingSystem = "Windows 11",
                            UserId = "u-002",
                            UserName = "Luis Perez",
                            UserPrincipalName = ""
                        });
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.PulseResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AnsweredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("LegacyValue")
                        .HasColumnType("int")
                        .HasColumnName("Value");

                    b.Property<int?>("NumericValue")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Responses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d6f6046-1aaf-44b4-92a1-7c174a5967cc"),
                            AnsweredAtUtc = new DateTimeOffset(new DateTime(2026, 6, 25, 14, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            CampaignId = new Guid("7f0f8595-44ae-4f1e-ae98-a098ac2bd601"),
                            Department = "Operaciones",
                            DeviceId = "pc-bog-001",
                            Email = "ana.torres@company.com",
                            EmployeeId = "",
                            EntraObjectId = "",
                            Hostname = "PC-BOG-001",
                            LegacyValue = 4,
                            NumericValue = 4,
                            QuestionId = new Guid("ca1508ea-1827-4f34-a846-f2f78da30603"),
                            QuestionText = "De 1 a 5, como te sientes hoy?",
                            QuestionType = 0,
                            SubmissionId = new Guid("bcfdceff-241e-417f-8487-3f6708e0f9f8"),
                            UserId = "u-001",
                            UserName = "Ana Torres",
                            UserPrincipalName = ""
                        },
                        new
                        {
                            Id = new Guid("7058e3cc-412b-41fd-b284-d9dcc385943e"),
                            AnsweredAtUtc = new DateTimeOffset(new DateTime(2026, 6, 24, 16, 56, 27, 804, DateTimeKind.Unspecified).AddTicks(729), new TimeSpan(0, 0, 0, 0, 0)),
                            CampaignId = new Guid("7f0f8595-44ae-4f1e-ae98-a098ac2bd601"),
                            Department = "Soporte",
                            DeviceId = "pc-med-021",
                            Email = "luis.perez@company.com",
                            EmployeeId = "",
                            EntraObjectId = "",
                            Hostname = "PC-MED-021",
                            LegacyValue = 5,
                            NumericValue = 5,
                            QuestionId = new Guid("ca1508ea-1827-4f34-a846-f2f78da30603"),
                            QuestionText = "De 1 a 5, como te sientes hoy?",
                            QuestionType = 0,
                            SubmissionId = new Guid("4b45881c-e9ea-4e71-b0df-e4eb5e17f770"),
                            UserId = "u-002",
                            UserName = "Luis Perez",
                            UserPrincipalName = ""
                        });
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.AdminSession", b =>
                {
                    b.HasOne("PulseCheck.Domain.Entities.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.DeliveryLog", b =>
                {
                    b.HasOne("PulseCheck.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("PulseCheck.Domain.Entities.PulseResponse", b =>
                {
                    b.HasOne("PulseCheck.Domain.Entities.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });
#pragma warning restore 612, 618
        }
    }
}
