variables:
  azureServiceConnection: 'sc-pulsecheck-dev'
  azureResourceGroup: 'SOL-SWA-APP-DEV'
  azureLocation: 'eastus2'
  azureEnvironmentName: 'pulsecheck-dev'
  aspNetCoreEnvironment: 'Development'
  deploymentEnvironmentName: 'dev'
  allowLocalOrigins: 'true'
  infraParametersFile: 'infra/dev.bicepparam'
  appServicePlanName: 'asp-swa-dev'
  appServiceName: 'swa-back-dev'
  staticWebAppName: 'swa-front-dev'
  staticWebAppCustomOrigin: ''
  applicationInsightsName: 'swa-back-dev'
  sqlServerName: 'sql-server-swa-dev'
  sqlDatabaseName: 'PulseCheckDb'
  sqlAdminUsername: 'pulsecheckadmin'
  fabricEndpoint: 'ens6zjjn2u6ujpv453hrhkxhvq-3ivrpnbzbcderi5p2rcbvht7e4.datawarehouse.fabric.microsoft.com'
  fabricDatabase: 'dw_people_hr'
  fabricCommandTimeoutSeconds: '30'
