variables:
  azureServiceConnection: 'sc-pulsecheck-prod'
  azureResourceGroup: 'SOL-PULSE-APP-PROD'
  azureLocation: 'eastus2'
  azureEnvironmentName: 'pulsecheck-prod'
  aspNetCoreEnvironment: 'Production'
  deploymentEnvironmentName: 'prod'
  allowLocalOrigins: 'false'
  infraParametersFile: 'infra/prod.bicepparam'
  appServicePlanName: 'ASP-Landstarapptest-abc0'
  appServiceName: 'pulse-back-prod'
  staticWebAppName: 'pulse-front-prod'
  staticWebAppCustomOrigin: 'https://pulsecheckapp.solvoglobal.com'
  applicationInsightsName: 'pulse-back-prod'
  sqlServerName: 'sql-server-pulsecheck-prod'
  sqlDatabaseName: 'PulseCheckDb'
  sqlAdminUsername: 'soladmin'
  entraTenantId: ''
  entraTenantDomain: ''
  entraApiClientId: ''
  entraWebClientId: ''
  fabricEndpoint: 'ens6zjjn2u6ujpv453hrhkxhvq-3ivrpnbzbcderi5p2rcbvht7e4.datawarehouse.fabric.microsoft.com'
  fabricDatabase: 'dw_people_hr'
  fabricCommandTimeoutSeconds: '30'
