variables:
  azureServiceConnection: 'sc-pulsecheck-prod'
  storageAccountName: 'pulsecheckaccountprod'
  agentPackagesContainerName: 'pulsecheck-agent-prod'
  agentPublishRuntime: 'win-x64'
  agentSelfContained: 'true'
  agentPackageFileName: 'PulseCheck.Agent-prod-$(Build.BuildId).zip'
  agentInstallerFileName: 'PulseCheck.exe'
  agentPackageLatestFileName: 'PulseCheck.Agent-prod.zip'
  agentInstallerLatestFileName: 'PulseCheck.Agent.Setup-prod.exe'
  agentPublicInstallerFileName: 'PulseCheck.exe'
  agentPollingIntervalSeconds: '60'
  agentLockedFirstAlertThresholdMinutes: '10'
  agentLockedAlertThresholdMinutes: '30'
  agentLockedDurationReportIntervalMinutes: '1'
  agentAutoUpdateEnabled: 'true'
  agentUpdateCheckIntervalMinutes: '120'
  agentUpdateFeedUrl: 'https://pulsecheckaccountprod.blob.core.windows.net/pulsecheck-agent-prod'
  agentLegacyUpdateManifestUrl: 'https://pulsecheckaccountprod.blob.core.windows.net/pulsecheck-agent-prod/agent-update.json'
  agentVelopackVersion: '0.0.1298'
